config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'import_purchases#index'

  resources :import_purchases
  get 'import_purchases/:id', to: 'import_purchases#show'
  get :purchases, to: 'purchases#index'
  get :customers, to: 'customers#index'
  get :itens, to: 'itens#index'
  get :merchants, to: 'merchants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :purchases

  validates :name, presence: true
end

app/models/import.rb
module Import
  class ProcessFail < StandardError; end

  def self.table_name_prefix
    'import_'
  end
end

app/models/import/purchase.rb
module Import
  class Purchase < ApplicationRecord
    include AASM

    has_many :lines,
             class_name: 'Import::PurchaseLine',
             dependent: :destroy,
             foreign_key: 'import_purchase_id'
    has_many :purchases, through: :lines

    has_one_attached :file

    validate :has_attached?, on: :create

    after_create :enqueue_import_purchase_worker

    aasm column: :state do
      state :waiting, initial: true
      state :processing
      state :completed
      state :completed_with_errors
      state :error

      event :process, before_transaction: :set_executed_on do
        transitions from: :waiting, to: :processing
      end

      event :complete do
        transitions from: :processing, to: :completed
      end

      event :complete_with_errors do
        transitions from: :processing, to: :completed_with_errors
      end

      event :error do
        transitions from: :waiting, to: :error
        transitions from: :processing, to: :error
      end
    end

    private

    def enqueue_import_purchase_worker
      Import::PurchaseWorker.perform_in(2.seconds, id)
    end

    def has_attached?
      return if file.attached?

      errors.add :file, 'not attached'
    end

    def set_executed_on
      update(executed_on: Date.current)
    end
  end
end

app/models/import/purchase_line.rb
module Import
  class PurchaseLine < ApplicationRecord
    include AASM

    belongs_to :import_purchase, class_name: 'Import::Purchase'
    belongs_to :purchase, class_name: '::Purchase', optional: true

    aasm column: :state do
      state :waiting, initial: true
      state :completed
      state :error

      event :complete do
        transitions from: :waiting, to: :completed
      end

      event :error do
        transitions from: :waiting, to: :error
      end
    end

    scope :failed, -> { where(state: :error) }
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :purchases

  validates :description, :price, presence: true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :purchases

  validates :name, :address, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :merchant

  def gross_income
    return 0 unless item.present?

    item.price * purchase_count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/controllers/import_purchases_controller.rb
class ImportPurchasesController < ApplicationController
  def index
    @import_purchase = Import::Purchase.new
    @imports_purchases = Import::Purchase.all
  end

  def create
    @import_purchase = Import::Purchase.new(permitted_params)

    if @import_purchase.save
      flash[:notice] =
        { Import::Purchase.model_name.human => ['Success created'] }
    else
      flash[:error] = @import_purchase.errors
    end

    redirect_to import_purchases_path
  end

  def show
    @import_purchase = Import::Purchase.find(params[:id])
  end

  private

  def permitted_params
    params.require(:import_purchase).permit(%i[name file])
  end
end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
  def index
    @itens = Item.all
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.preload(:item, :customer, :merchant).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_customers.html.erb
<div class='card'>
  <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
    <thead class='table-dark bg-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'><%= Customer.human_attribute_name(:name) %></th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <th scope='row'><%= customer.id %></th>
          <td><%= customer.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/index.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Models</li>
          <li class='breadcrumb-item active' aria-current='page'>Customers</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <%= render 'customers' %>
</div>

app/views/import_purchases/_form.html.erb
<%= form_for @import_purchase do |f| %>
  <form>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter your import purchase name ..' %>
    </div>
    <div class='form-group'>
      <%= f.label :file %>
      <%= f.file_field :file, placeholder: 'Enter your file ..' %>
    </div>
    <%= f.submit 'New Importatiom', class: 'btn btn-primary', data: { disable_with: 'Wait...' } %>
  </form>
<% end %>

app/views/import_purchases/_imports_purchase.html.erb
<div class='card'>
  <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
    <thead class='table-dark bg-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'><%= Import::Purchase.human_attribute_name(:name) %></th>
        <th scope='col'><%= Import::Purchase.human_attribute_name(:state) %></th>
        <th scope='col'><%= Import::Purchase.human_attribute_name(:executed_on) %></th>
        <th scope='col'>Total gross income</th>
        <th scope='col'><%= Import::Purchase.human_attribute_name(:file) %></th>
        <th scope='col'></th>
      </tr>
    </thead>

    <tbody>
      <% @imports_purchases.each do |import_purchase| %>
        <tr>
          <th scope='row'><%= import_purchase.id %></th>
          <td><%= import_purchase.name %></td>
          <td><%= import_purchase.state %></td>
          <td><%= l(import_purchase.executed_on) if import_purchase.executed_on.present? %></td>
          <td><%= number_to_currency(import_purchase.purchases.sum(&:gross_income)) %></td>
          <td><%= link_to 'download', url_for(import_purchase.file) %></td>
          <td><%= link_to 'details', import_purchase %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/import_purchases/index.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Importers</li>
          <li class='breadcrumb-item active' aria-current='page'>Purchases Imports</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <% if flash.any? %>
    <% flash.each do |name, msgs| %>
      <div class="alert alert-<%=name.eql?('error') ? 'danger' : 'success'%>" role="alert">
        <% if msgs.instance_of? Hash %>
          <% msgs.each do |field, message| %>
            <p><%= "#{field.titleize}: #{message.join(', ')}" %></p>
          <% end %>
        <% else %>
          <p><%= msgs %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class='card card-form'>
    <div class='row no-gutters'>
      <div class='col-lg-4 card-body'>
        <p><strong class='headings-color'>Purchase Imports</strong></p>
        <p class='text-muted'>You've received a <a href='https://gitlab.com/nuuvem-public/tests/web-1/-/blob/master/example_input.tab' target='_blank'>text file (tab separated)</a> with data describing the company sales. We need a way for this data to be imported to a database.</p>
      </div>
      <div class='col-lg-8 card-form__body card-body'>
        <%= render 'form' %>
      </div>
    </div>
  </div>

  <%= render 'imports_purchase' %>
</div>

app/views/import_purchases/show.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Importers</li>
          <li class='breadcrumb-item' aria-current='page'>Purchases Imports</li>
          <li class='breadcrumb-item active' aria-current='page'>#<%= @import_purchase.id %></li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <div class='card card-form'>
    <div class='row no-gutters'>
      <div class='col-lg-4 card-body'>
        <div class='form-group'>
          <b><label for="import_purchase_name"><%= Import::Purchase.human_attribute_name(:name) %></label></b>
          <%= @import_purchase.name %>
        </div>

        <div class='form-group'>
          <b><label for="import_purchase_state"><%= Import::Purchase.human_attribute_name(:state) %></label></b>
          <%= @import_purchase.state %>
        </div>

        <div class='form-group'>
          <b><label for="import_purchase_executed_on"><%= Import::Purchase.human_attribute_name(:executed_on) %></label></b>
          <%= @import_purchase.executed_on %>
        </div>

        <div class='form-group'>
          <b><label for="import_purchase_total_gross_income">Total gross income</label></b>
          <%= number_to_currency(@import_purchase.purchases.sum(&:gross_income)) %>
        </div>

        <div class='form-group'>
          <b><label for="import_purchase_file"><%=Import::Purchase.human_attribute_name(:file) %></label></b>
          <%= link_to 'download', url_for(@import_purchase.file) %>
        </div>
      </div>
    </div>
  </div>

  <div class='card card-form'>
    <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
      <thead class='table-dark bg-dark'>
        <tr>
          <th scope='col'>#</th>
          <th scope='col'><%= Purchase.model_name.human %></th>
          <th scope='col'><%= Import::PurchaseLine.human_attribute_name(:state) %></th>
          <th scope='col'><%= Import::PurchaseLine.human_attribute_name(:message) %></th>
        </tr>
      </thead>

      <tbody>
        <% @import_purchase.lines.each do |line| %>
          <tr>
            <th scope='row'><%= line.id %></th>
            <td><%= line.purchase_id %></td>
            <td><%= line.state %></td>
            <td><%= line.message %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/itens/_itens.html.erb
<div class='card'>
  <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
    <thead class='table-dark bg-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'><%= Item.human_attribute_name(:description) %></th>
        <th scope='col'><%= Item.human_attribute_name(:price) %></th>
      </tr>
    </thead>

    <tbody>
      <% @itens.each do |item| %>
        <tr>
          <th scope='row'><%= item.id %></th>
          <td><%= item.description %></td>
          <td><%= number_to_currency(item.price) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/itens/index.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Models</li>
          <li class='breadcrumb-item active' aria-current='page'>Itens</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <%= render 'itens' %>
</div>

app/views/layouts/_drawer_left.html.erb
<div class='mdk-drawer js-mdk-drawer' id='default-drawer' data-align='start'>
  <div class='mdk-drawer__content'>
    <div class='sidebar sidebar-light sidebar-left simplebar' data-simplebar>
      <div class='sidebar-heading sidebar-m-t'>Importers</div>

      <ul class='sidebar-menu'>
        <li class='sidebar-menu-item active'>
          <a class='sidebar-menu-button' href='<%= root_path %>'>
            <i class='sidebar-menu-icon sidebar-menu-icon--left material-icons'>dvr</i>
            <span class='sidebar-menu-text'>Purchases Imports</span>
          </a>
        </li>
      </ul>

      <div class='sidebar-heading sidebar-m-t'>Models</div>
      <ul class='sidebar-menu'>
        <li class='sidebar-menu-item active'>
          <a class='sidebar-menu-button' href='<%= purchases_path %>'>
            <i class='sidebar-menu-icon sidebar-menu-icon--left material-icons'>dvr</i>
            <span class='sidebar-menu-text'>Purchases</span>
          </a>
          <a class='sidebar-menu-button' href='<%= customers_path %>'>
            <i class='sidebar-menu-icon sidebar-menu-icon--left material-icons'>dvr</i>
            <span class='sidebar-menu-text'>Customers</span>
          </a>
          <a class='sidebar-menu-button' href='<%= itens_path %>'>
            <i class='sidebar-menu-icon sidebar-menu-icon--left material-icons'>dvr</i>
            <span class='sidebar-menu-text'>Itens</span>
          </a>
          <a class='sidebar-menu-button' href='<%= merchants_path %>'>
            <i class='sidebar-menu-icon sidebar-menu-icon--left material-icons'>dvr</i>
            <span class='sidebar-menu-text'>Merchants</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class='navbar navbar-expand-sm navbar-main navbar-dark bg-dark pr-0' id='navbar' data-primary>
  <div class='container-fluid p-0'>
    <button class='navbar-toggler navbar-toggler-right d-block d-md-none' type='button' data-toggle='sidebar'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <a href='<%= root_path %>' class='navbar-brand'>
      <span>Purchase Importer</span>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en' dir='ltr'>
  <head>
    <title>Purchase Importer</title>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= @body_class || 'layout-default' %>'>
    <div class='mdk-header-layout js-mdk-header-layout'>
      <div id='header' class='mdk-header js-mdk-header m-0' data-fixed>
        <div class='mdk-header__content'>
          <%= render 'layouts/navbar'%>
        </div>
      </div>

      <div class='mdk-header-layout__content'>
        <div class='mdk-drawer-layout js-mdk-drawer-layout' data-push data-responsive-width='992px'>
          <div class='mdk-drawer-layout__content page'>
            <%= yield %>
          </div>

          <%= render 'layouts/drawer_left' %>
        </div>
      </div>
    </div>

    <%= content_for :footer %>

    <%= javascript_include_tag 'core-scripts', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= content_for :footer_scripts %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang='en' dir='ltr'>
  <head>
    <title>Purchase Importer</title>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= @body_class || 'layout-fluid' %>'>
    <%= yield %>
  </body>
</html>

app/views/merchants/_merchants.html.erb
<div class='card'>
  <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
    <thead class='table-dark bg-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'><%= Merchant.human_attribute_name(:name) %></th>
        <th scope='col'><%= Merchant.human_attribute_name(:address) %></th>
      </tr>
    </thead>

    <tbody>
      <% @merchants.each do |merchant| %>
        <tr>
          <th scope='row'><%= merchant.id %></th>
          <td><%= merchant.name %></td>
          <td><%= merchant.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/merchants/index.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Models</li>
          <li class='breadcrumb-item active' aria-current='page'>Merchants</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <%= render 'merchants' %>
</div>

app/views/purchases/_purchases.html.erb
<div class='card'>
  <table class='table table-striped table-bordered table-hover' style='margin-bottom: 0;'>
    <thead class='table-dark bg-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'><%= Customer.model_name.human %></th>
        <th scope='col'><%= Item.human_attribute_name(:description) %></th>
        <th scope='col'><%= Item.human_attribute_name(:price) %></th>
        <th scope='col'><%= Purchase.human_attribute_name(:purchase_count) %></th>
        <th scope='col'><%= Merchant.human_attribute_name(:address) %></th>
        <th scope='col'><%= Merchant.model_name.human %></th>
        <th scope='col'>Gross income</th>
      </tr>
    </thead>

    <tbody>
      <% @purchases.each do |purchase| %>
        <tr>
          <th scope='row'><%= purchase.id %></th>
          <td><%= purchase.customer.name %></td>
          <td><%= purchase.item.description %></td>
          <td><%= number_to_currency(purchase.item.price) %></td>
          <td><%= purchase.purchase_count %></td>
          <td><%= purchase.merchant.address %></td>
          <td><%= purchase.merchant.name %></td>
          <td><%= number_to_currency(purchase.gross_income) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/purchases/index.html.erb
<div class='container-fluid page__heading-container'>
  <div class='page__heading d-flex align-items-center'>
    <div class='flex'>
      <nav aria-label='breadcrumb'>
        <ol class='breadcrumb mb-0'>
          <li class='breadcrumb-item' aria-current='page'>Models</li>
          <li class='breadcrumb-item active' aria-current='page'>Purchases</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class='container-fluid page__container'>
  <%= render 'purchases' %>
</div>